### ISSUE TITLE
Absolute import on each packages

### ISSUE THREAD

**Issue by sondh0127** [tiagob/create-full-stack#151]
We want to use "absolute import" inside each package. Like

web/tsconfig.json
```
baseUrl": "./"
```

so we can
```javascript
import {Theme} from 'src/theme' 
=> ('packages/web/src/theme')
```
from web packages

Is there any alternative approach? like change the root `tsconfig.json`

**Comment by tiagob** [comment]
To make changes relative to the package you'll have to modify the package `tsconfig.json`s. So for your `packages/web` example:

Modify `packages/web/tsconfig.json` to

```json
{
  "extends": "../../tsconfig",
  "compilerOptions": {
    "baseUrl": "./"
  }
}
```

This will trigger eslint errors which you can remove by modifying `estlintrc.js` to

```js
module.exports = {
  extends: "eslint-config-create-full-stack",
  rules: {
    "import/no-unresolved": "off",
  },
};
```

TS baseUrl docs: https://www.typescriptlang.org/docs/handbook/module-resolution.html#base-url
