### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by austinrivas** [tiagob/create-full-stack#162]
I would love to start contributing to this project, but the code base is a little inaccessible without documentation.

Are there any resources available explaining the generator structure you chose and how we can start extending it?

**Comment by tiagob** [comment]
Great to hear! Totally fair. It's not documented.

A quick overview.

The entry point is here:
https://github.com/tiagob/create-full-stack/blob/master/packages/create-full-stack/src/index.ts

There 4 main templates. Each is a combination of backend and auth. Namely:

- cfs-template-apollo-server-express-auth0
- cfs-template-apollo-server-express-no-auth
- cfs-template-hasura-auth0
- cfs-template-hasura-no-auth

You can find these along with common libraries under packages:
https://github.com/tiagob/create-full-stack/tree/master/packages

I can cover the structure more over Zoom and answer any questions you have. Are you free to chat sometime? Can you email me@tiagobandeira.com?

**Comment by austinrivas** [comment]
I don't know if I will be able to do zoom, I'm based out of bangkok and the time difference is pretty extreme.

I'll shoot you and email, but we can also just use this thread if you want.
