### ISSUE TITLE
Pulumi Hasura Cloud Provider

### ISSUE THREAD

**Issue by austinrivas** [tiagob/create-full-stack#165]
**Is your feature request related to a problem? Please describe.**
I would like to be able to manage and provision hasura cloud via Pulumi.

**Describe the solution you'd like**
It seems like the recommended practice by pulumi is to define a Hasura provider that can be used in deploy scripts

**Describe alternatives you've considered**
I am currently managing Hasura cloud deployments via GH actions and custom TS scripts that wrap the hasura cli.

**Additional context**
Definitely willing to collaborate on this, right now I am digging into how pulumi providers work.

**Comment by tiagob** [comment]
How would you like to split this up? Do you have some commands terminal
commands you’re using today? Does Hasura have an API we could use?

**Comment by austinrivas** [comment]
The hasura cloud api is documented here https://hasura.io/docs/1.0/graphql/cloud/api-reference.html

Its pretty simple, just crud for "tenets" which are just hasura instances, and get / set for env vars.

The part that I am hung up on is how to implement the pulumi provider to be able to diff the current configuration and apply updates.

Currently I am using shelljs to execute these commands via typescript, but it doesn't integrate into pulumi's diffing system.

Do you have any experience developing pulumi providers?
