### ISSUE TITLE
Hasura TS Metadata SDK

### ISSUE THREAD

**Issue by austinrivas** [tiagob/create-full-stack#166]
My team is working migrating our static yaml hasura metadata files to be generated from the new Hasura Metadata SDK instead.

https://github.com/hasura/graphql-engine/tree/master/contrib/metadata-types

This lets use DRY out our metadata and unit test our more complex permissions.

Once we are done I will be sure to share and we can work on integrating it into the hasura template you already have.

**Comment by tiagob** [comment]
👍
